version: '3.8'

services:
  pyscipopt:
    image: pyscipopt:4.0.0
    build: .
    network_mode: "none"
    volumes:
      - type: bind
        source: ./
        target: /home/user
        read_only: true

